version: '3.8'

services:
  web:
    build: ./
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app/
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web